#!/usr/bin/env bash
set -euo pipefail

echo "=================================================="
echo "DocuFlex CI Permission & Security Verifier"
echo "=================================================="

MANIFEST_FILE="android/app/src/main/AndroidManifest.xml"

if [ ! -f "$MANIFEST_FILE" ]; then
    echo "ERROR: Manifest file not found at $MANIFEST_FILE"
    exit 1
fi

MANIFEST_FILES=("$MANIFEST_FILE")

# Search for any merged manifests generated by Gradle (debug or release)
MERGED_DIR="android/app/build/intermediates/merged_manifests"
if [ -d "$MERGED_DIR" ]; then
    while IFS= read -r -d '' f; do
        MANIFEST_FILES+=("$f")
    done < <(find "$MERGED_DIR" -name "AndroidManifest.xml" -print0)
fi

for TARGET in "${MANIFEST_FILES[@]}"; do
    echo "Auditing manifest: $TARGET"

    # 1. Audit against INTERNET permission
    if grep -Eiq "<uses-permission[^>]+android.permission.INTERNET" "$TARGET"; then
        echo "FAILED: android.permission.INTERNET was declared in $TARGET!"
        exit 1
    fi
    echo "✓ PASSED: No android.permission.INTERNET declared in $TARGET."

    # 2. Audit against Broad Storage permissions
    if grep -Eiq "<uses-permission[^>]+(READ_EXTERNAL_STORAGE|MANAGE_EXTERNAL_STORAGE|WRITE_EXTERNAL_STORAGE)" "$TARGET"; then
        echo "FAILED: Broad external storage permission detected in $TARGET! DocuFlex strictly uses SAF."
        exit 1
    fi
    echo "✓ PASSED: Zero broad storage permissions in $TARGET (Storage Access Framework confirmed)."

    # 3. Audit against Dangerous Spyware permissions (Mic, Camera, SMS, Location)
    for PERM in "CAMERA" "RECORD_AUDIO" "ACCESS_FINE_LOCATION" "READ_SMS" "READ_CONTACTS"; do
        if grep -Eiq "<uses-permission[^>]+$PERM" "$TARGET"; then
            echo "FAILED: Dangerous permission $PERM detected in $TARGET!"
            exit 1
        fi
    done
    echo "✓ PASSED: Zero sensor/tracking permissions in $TARGET."

    # 4. Verify allowBackup is set to false
    if ! grep -qi 'android:allowBackup="false"' "$TARGET"; then
        echo "FAILED: allowBackup must be set to false for privacy protection in $TARGET!"
        exit 1
    fi
    echo "✓ PASSED: allowBackup=\"false\" confirmed in $TARGET."
done

echo "=================================================="
echo "SECURITY AUDIT COMPLETED SUCCESSFULLY: 100% OFFLINE"
echo "=================================================="
